SellingwithEntityframwork/Models/PD_ORDER.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SellingwithEntityframwork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PD_ORDER
    {
        public string OD_ID { get; set; }
        public string PD_ID { get; set; }
        public Nullable<System.DateTime> OD_DATE { get; set; }
        public Nullable<decimal> OD_QUANTITY { get; set; }
        public Nullable<decimal> PRICE { get; set; }
        public string OD_STATUS { get; set; }
    }
}

SellingwithEntityframwork/Controllers/PD_ORDERController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Newtonsoft.Json;
using SellingwithEntityframwork.Models;

namespace SellingwithEntityframwork.Controllers
{
    public class PD_ORDERController : Controller
    {
        private ProductionEntities db = new ProductionEntities();

        // GET: PD_ORDER
        public ActionResult MainOrder()
        {
            if (db.PD_ORDER.AsEnumerable().Where(x => (x.OD_DATE.HasValue ? x.OD_DATE.Value.ToShortDateString() : "") == DateTime.Now.ToShortDateString()).ToList().Count != 0)
            {
                ViewData["listORder"] = db.PD_ORDER.AsEnumerable().Where(x => (x.OD_DATE.HasValue ? x.OD_DATE.Value.ToShortDateString() : "") == DateTime.Now.ToShortDateString()).ToList();
            }
            else
            {
                ViewData["listORder"] = null;
            }
            ViewData["listTYPE"] = db.PD_TYPE.ToList();
            ViewData["listPRODUCT"] = db.PD_PRODUCT.ToList();
            return View();
        }
        public class GetOrderDataClass
        {

            public int Number { get; set; }
            public string ProdcutID { get; set; }
            public string ProdcutName { get; set; }
            public string Quantity { get; set; }
            public string Price { get; set; }
            public string Type { get; set; }
            public string Unit { get; set; }
        }
        public JsonResult GetOrderData(string oderid)
        {

            List<GetOrderDataClass> Data = new List<GetOrderDataClass>();
            int i = 1;
            var dbproduct = db.PD_PRODUCT.ToList();
            var dbtype = db.PD_TYPE.ToList();
            foreach (var item in db.PD_ORDER.AsEnumerable().Where(x => x.OD_ID == oderid).ToList())
            {
                GetOrderDataClass dt = new GetOrderDataClass();
                dt.Number = i;
                dt.ProdcutID = item.PD_ID;
                dt.ProdcutName = dbproduct.Where(x => x.PD_ID == item.PD_ID).FirstOrDefault().PD_NAME;
                dt.Quantity = item.OD_QUANTITY.ToString();
                dt.Price = item.PRICE.ToString();
                dt.Type = dbproduct.Where(x => x.PD_ID == item.PD_ID).FirstOrDefault().TP_ID + " " + dbtype.Where(x => x.TP_ID == dbproduct.Where(q => q.PD_ID == item.PD_ID).FirstOrDefault().TP_ID).FirstOrDefault().TP_NAME;
                dt.Unit = dbproduct.Where(x => x.PD_ID == item.PD_ID).FirstOrDefault().PD_UNIT;
                i++;
                Data.Add(dt);

            }

            string strdatajsonOrder = JsonConvert.SerializeObject(Data);

            return Json(new { strjsondata = strdatajsonOrder, orderid = oderid });
        }
        public class ClassGetGroupOrderData
        {
            public int Number { get; set; }
            public string OrderID { get; set; }
            public string Date { get; set; }
            public string pricesum { get; set; }
        }
        public JsonResult GetGroupOrderData()
        {
            List<ClassGetGroupOrderData> data = new List<ClassGetGroupOrderData>();
            int i = 1;
            var PD_orderDB = db.PD_ORDER.AsEnumerable().Where(x => (x.OD_DATE.HasValue ? x.OD_DATE.Value.ToShortDateString() : "") == DateTime.Now.ToShortDateString()).ToList();
            var GropPD_ORDER = db.PD_ORDER.AsEnumerable().Where(x => (x.OD_DATE.HasValue ? x.OD_DATE.Value.ToShortDateString() : "") == DateTime.Now.ToShortDateString()).GroupBy(x => x.OD_ID);
            foreach (var item in GropPD_ORDER)
            {
                ClassGetGroupOrderData dt = new ClassGetGroupOrderData();
                dt.Number = i;
                dt.OrderID = item.Key;
                dt.Date = PD_orderDB.Where(x => x.OD_ID == item.Key).FirstOrDefault().OD_DATE.Value.ToShortDateString();
                dt.pricesum = PD_orderDB.Where(x => x.OD_ID == item.Key).Sum(x => x.PRICE).ToString();
                i++;
                data.Add(dt);
            }
            string strdatajsonOrder = JsonConvert.SerializeObject(data);
            return Json(new { strjsondata = strdatajsonOrder});
        }
        public ActionResult Index()
        {
            ViewData["listTYPE"] = db.PD_TYPE.ToList();
            ViewData["listPRODUCT"] = db.PD_PRODUCT.ToList();
            return View(db.PD_ORDER.ToList());
        }

        public ActionResult Details(string id1, string id2)
        {
            if (id1 == null || id2 == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            PD_ORDER pD_ORDER = db.PD_ORDER.Where(x => x.OD_ID == id1 && x.PD_ID == id2).FirstOrDefault();
            if (pD_ORDER == null)
            {
                return HttpNotFound();
            }
            return View(pD_ORDER);
        }

        public class Iteminorder 
        { 
            public string PD_ID { get; set; }
            public string TP_ID { get; set; }
            public string QUNTITY { get; set; }
            public string PRICE { get; set; }
        }

        public JsonResult InputProductToOrder(string JsonlistProduct) 
        {
            List<PD_PRODUCT> listProduct = JsonConvert.DeserializeObject<List<PD_PRODUCT>>(JsonlistProduct);
            var Iteminsame = listProduct.GroupBy(x => new { x.PD_ID }).ToList();
            List<Iteminorder> iteminorder = new List<Iteminorder>();
            var dbproduct = db.PD_PRODUCT.ToList();
            string OD_ID = "";
            bool checkfuntion = false;
            foreach (var item in Iteminsame) 
            {
                if(dbproduct.Where(x => x.PD_ID == item.Key.PD_ID).FirstOrDefault() != null) 
                {
                    Iteminorder dt = new Iteminorder();
                    dt.PD_ID = item.Key.PD_ID;
                    dt.TP_ID = dbproduct.Where(x => x.PD_ID == item.Key.PD_ID).FirstOrDefault().TP_ID;
                    dt.QUNTITY = listProduct.Where(x => x.PD_ID == item.Key.PD_ID).ToList().Count.ToString();
                    decimal price = (dbproduct.Where(x => x.PD_ID == item.Key.PD_ID).FirstOrDefault().PD_PRICE??0);
                    string strprice = (price.ToString()  ?? "0") ;
                    dt.PRICE = (decimal.Parse(strprice) * decimal.Parse(dt.QUNTITY)).ToString();
                    iteminorder.Add(dt);
                }

            }
            
            if (db.PD_ORDER.ToList().Count!=0)
            {
                var lastid = db.PD_ORDER.OrderByDescending(x => x.OD_ID).FirstOrDefault();
                string lastnumberid = lastid.OD_ID.Substring(6);
                int lastnumberidINT = int.Parse(lastnumberid) + 1;
                int checkmaxlenght = lastnumberidINT.ToString().Length;
                OD_ID = "OD" + DateTime.Now.Year.ToString();
                for (int i = checkmaxlenght; i < 4; i++)
                {
                    OD_ID += "0";
                }
                OD_ID += lastnumberidINT;
         
                foreach (var item in iteminorder) 
                {
                    PD_ORDER pD_ORDER = new PD_ORDER();
                    pD_ORDER.OD_ID = OD_ID;
                    pD_ORDER.PD_ID = item.PD_ID;
                    pD_ORDER.OD_QUANTITY = decimal.Parse(item.QUNTITY);
                    pD_ORDER.PRICE = decimal.Parse(item.PRICE);
                    pD_ORDER.OD_DATE = DateTime.Now;
                    CreateToOrder(pD_ORDER);
                    PD_PRODUCT pD_PRODUCT = db.PD_PRODUCT.Find(item.PD_ID);
                    pD_PRODUCT.PD_VALUE = pD_PRODUCT.PD_VALUE - pD_ORDER.OD_QUANTITY;
                    FuntionEdit(pD_PRODUCT);
                    checkfuntion = true;
                }
               
            }
            else
            {
                OD_ID = "OD" + DateTime.Now.Year.ToString() +"0001";

                foreach (var item in iteminorder)
                {
                    PD_ORDER pD_ORDER = new PD_ORDER();
                    pD_ORDER.OD_ID = OD_ID;
                    pD_ORDER.PD_ID = item.PD_ID;
                    pD_ORDER.OD_QUANTITY = decimal.Parse(item.QUNTITY);
                    pD_ORDER.PRICE = decimal.Parse(item.PRICE);
                    pD_ORDER.OD_DATE = DateTime.Now;
                    CreateToOrder(pD_ORDER);
                    PD_PRODUCT pD_PRODUCT = db.PD_PRODUCT.Find(item.PD_ID);
                    pD_PRODUCT.PD_VALUE = pD_PRODUCT.PD_VALUE - pD_ORDER.OD_QUANTITY;
                    FuntionEdit(pD_PRODUCT);
                    checkfuntion = true;
                }
               
            }
            return Json(new { success = checkfuntion, orderid = OD_ID });
        }
        public string FuntionEdit([Bind(Include = "PD_ID,PD_NAME,PD_VALUE,PD_PRICE,TP_ID,PD_UNIT")] PD_PRODUCT pD_PRODUCT)
        {
            string ok = "";
            if (ModelState.IsValid)
            {
                db.Entry(pD_PRODUCT).State = EntityState.Modified;
                db.SaveChanges();
                ok = "Update Store ok";
            }

            return ok;
        }

        public string CreateToOrder([Bind(Include = "OD_ID,PD_ID,OD_DATE,OD_QUANTITY,PRICE")] PD_ORDER pD_ORDER)
        {
            string ok = "";
            if (ModelState.IsValid)
            {
                db.PD_ORDER.Add(pD_ORDER);
                db.SaveChanges();
                ok = "Insert Order ok";
            }

            return ok;
        }
        public ActionResult Edit(string id1,string id2)
        {
            if (id1 == null || id2 == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PD_ORDER pD_ORDER = db.PD_ORDER.Where(x=>x.OD_ID==id1&&x.PD_ID==id2).FirstOrDefault();
            if (pD_ORDER == null)
            {
                return HttpNotFound();
            }
            return View(pD_ORDER);
        }

SellingwithEntityframwork/Views/PD_ORDER/Delete.cshtml
@model SellingwithEntityframwork.Models.PD_ORDER

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>PD_ORDER</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.OD_ID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OD_ID)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PD_ID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PD_ID)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.OD_DATE)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OD_DATE)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OD_QUANTITY)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OD_QUANTITY)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PRICE)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PRICE)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

SellingwithEntityframwork/Views/PD_ORDER/Details.cshtml
@model SellingwithEntityframwork.Models.PD_ORDER

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>PD_ORDER</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.OD_ID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OD_ID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PD_ID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PD_ID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OD_DATE)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OD_DATE)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OD_QUANTITY)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OD_QUANTITY)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PRICE)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PRICE)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    @Html.ActionLink("Back to List", "Index")
</p>

SellingwithEntityframwork/Views/PD_ORDER/MainOrder.cshtml
@using Newtonsoft.Json
@{
    ViewBag.Title = "MainOrder";
    IEnumerable<SellingwithEntityframwork.Models.PD_PRODUCT> PRODUCTLIST = (IEnumerable<SellingwithEntityframwork.Models.PD_PRODUCT>)ViewData["listPRODUCT"];
    IEnumerable<SellingwithEntityframwork.Models.PD_TYPE> TYPELIST = (IEnumerable<SellingwithEntityframwork.Models.PD_TYPE>)ViewData["listTYPE"];
    IEnumerable<SellingwithEntityframwork.Models.PD_ORDER> ODERLIST = (IEnumerable<SellingwithEntityframwork.Models.PD_ORDER>)ViewData["listORder"];
    string strJsonPRODUCTLIST = JsonConvert.SerializeObject(PRODUCTLIST);
}

<div>
    <div style="text-align:center">
        <h2> รายการสินค้า </h2>
    </div>

    <table class="table" id="tableproduct">

        <thead>
            <tr>
                <th>
                </th>
                <th>
                    รหัสสินค้า
                </th>
                <th>
                    ชื่อสินค้า
                </th>
                <th>
                    จำนวน
                </th>
                <th>
                    ราคา
                </th>
                <th>
                    รหัสประเภทสินค้า
                </th>
                <th>
                    หน่วย
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @{int i = 1; }
            @foreach (var item in PRODUCTLIST)
            {
                <tr>
                    <td class="itemadd">
                        <input type="button" class="btn btn-success add" onclick="clicktoorder(this)" value="+">
                    </td>
                    <td class="PD_ID">
                        @Html.DisplayFor(modelItem => item.PD_ID)
                    </td>
                    <td class="PD_NAME">
                        @Html.DisplayFor(modelItem => item.PD_NAME)
                    </td>
                    <td id="ID_VALUE_@item.PD_ID" class="PD_VALUE">
                        @Html.DisplayFor(modelItem => item.PD_VALUE)
                    </td>
                    <td class="PD_PRICE">
                        @Html.DisplayFor(modelItem => item.PD_PRICE)
                    </td>
                    <td class="TP_ID">
                        @Html.DisplayFor(modelItem => item.TP_ID)
                        @if (TYPELIST.Where(x => x.TP_ID == item.TP_ID).FirstOrDefault() != null)
                        {
                            @TYPELIST.Where(x => x.TP_ID == item.TP_ID).FirstOrDefault().TP_NAME
                        }
                    </td>
                    <td class="PD_UNIT">
                        @Html.DisplayFor(modelItem => item.PD_UNIT)
                    </td>

                </tr>
            }
        </tbody>


    </table>
</div>

<div>
    <div style="text-align:center">
        <h2>เออเดอร์รายการสินค้า</h2>
        <label id="orderid"></label>
    </div>
    <input type="button" class="btn btn-warning col-sm-1" onclick="refeshandclear()" value="Clear" disabled id="clearitem">
    <table class="table" id="tableproducttoOrder">
        <thead>
            <tr>
                <th>
                    จำนวนรายการที่สั่ง
                </th>
                <th>
                    รหัสสินค้า
                </th>
                <th>
                    ชื่อสินค้า
                </th>
                <th>
                    จำนวน
                </th>
                <th>
                    ราคา
                </th>
                <th>
                    รหัสประเภทสินค้า
                </th>
                <th>
                    หน่วย
                </th>
                <th></th>

            </tr>
        </thead>
        <tbody id="tbodyPDorder">
        </tbody>
        <tfoot>
            <tr>
                <td>
                    ทั้งหมด : 
                    <br><label id="CountPD"></label> รายการ
                </td>
                <td>
                </td>
                <td>
                </td>
                <td>
                </td>
                <td>
                   รวม <label id="CountPcire"></label>
                </td>
                <td>
                    <br>
                    <label id="Units">BTH</label>
                </td>
                <td>
                </td>
                <td>
                </td>
            </tr>
        </tfoot>
    </table>
    <input type="button" class="btn btn-primary col-sm-1" value="Create" onclick="Createorder()" disabled id="Creorder">
    <br>
</div>


<div>
    <div style="text-align:center">
        <h2>รายเออเดอร์วันนี้</h2>
  
    </div>

    <table class="table" id="tableOrder">
        <thead>
            <tr>
                <th>
                </th>
                <th>
                    จำนวน ออเดอร์
                </th>
                <th>
                    รหัสออเดอร์
                </th>

                <th>
                    วันที่
                </th>
                <th>
                    ราคา
                </th>
            </tr>
        </thead>
        <tbody id="thobyoorderbottom">
            @{ 
                int orderumber = 1;



} 
            @if(ODERLIST!=null)
            {
                foreach (var item in ODERLIST.GroupBy(x => new { x.OD_ID }).ToList())
                {
                <tr>
                    <td >
                        <input type="button" class="btn btn-success add" onclick="EvnetclickgetorderHistory(this)" value="Show">
                    </td>
                    <td >
                        @orderumber
                    </td>
                    <td class="orderidHIS">
                        @Html.DisplayFor(modelItem => item.Key.OD_ID)
                    </td>
                    <td >
                        @DateTime.Now.ToShortDateString()
                    </td>
                    <td >
                        @ODERLIST.Where(x=>x.OD_ID==item.Key.OD_ID).Sum(x => x.PRICE)
                    </td>


                </tr>
                    orderumber++;
                }
            }
        </tbody>
    </table>
    <br>
</div>
@Scripts.Render("~/bundles/jquery")
<script>

    function rejectitem(e)
    {
        var selectedRow = e.parentNode.parentNode;
        var parentNode = selectedRow.parentNode;
        var columns = selectedRow.querySelectorAll("td");
        var data = [];
        for (var i = 0; i < columns.length - 1; i++) {
            data.push(columns[i].textContent);
        }
        console.log(data);
        var idselect = "ID_VALUE_"+ data[1];
        var countCell = document.querySelector("#tableproduct #" + idselect);
        countCell.innerHTML = parseInt(countCell.innerHTML) + 1;
        parentNode.removeChild(selectedRow);
        $("#CountPD").text((parseInt($("#CountPD").text().trim()) - 1));
        $("#CountPcire").text((parseInt($("#CountPcire").text().trim()) - parseInt(data[4])));
        table = document.getElementById("tbodyPDorder");
        var row = table.rows.length;
        if (row==0)
        {
            document.getElementById("Creorder").disabled = true;
        }
    }

    function clicktoorder(e) {
        // Get the item data from table A, for example assuming the item have the id and name
        var check = $('#orderid').text().trim();
        if (check != "")
        {
            $("#tbodyPDorder").empty();
        }
        $('#orderid').text('');
        var storevalue = parseFloat($(e).closest('tr').find('.PD_VALUE').text().trim());
        if (storevalue === 0) {
            $(e).closest('tr').find('.itemadd').text('')
            alert("สินค้าไม่พอ");
        } else {
            storevalue = storevalue - 1;
            console.log(e);
            var PD_ID = $(e).closest('tr').find('.PD_ID').text().trim();
            var PD_NAME = $(e).closest('tr').find('.PD_NAME').text().trim();
            var PD_VALUE = '1';
            var PD_PRICE = $(e).closest('tr').find('.PD_PRICE').text().trim();
            var TP_ID = $(e).closest('tr').find('.TP_ID').text().trim();
            var PD_UNIT = $(e).closest('tr').find('.PD_UNIT').text().trim();
            var table = document.getElementById("tableproducttoOrder");
            var count = table.rows.length-1;
            var newRow = '<tr> <td>' + count + '</td><td>' + PD_ID + '</td><td>' + PD_NAME + '</td><td>' + PD_VALUE + '</td><td>' + PD_PRICE + '</td><td>' + TP_ID + '</td><td>' + PD_UNIT + '</td> <td>  <input type="button" class="btn btn-danger add" onclick="rejectitem(this)" value="-"> </td> </tr>';
            console.log(storevalue);
            $(e).closest('tr').find('.PD_VALUE').text('');
            $(e).closest('tr').find('.PD_VALUE').text(storevalue);
            $('#tableproducttoOrder').append(newRow);
            $('#CountPD').text(count);
            table = document.getElementById("tableproducttoOrder");
            var total = 0;
            for (var i = 1; i < table.rows.length-1; i++) {
                console.log(table.rows[i].cells[4].innerHTML.trim());
                total += parseFloat(table.rows[i].cells[4].innerHTML.trim());
            }
            console.log(total);
            $('#CountPcire').text(total);
            document.getElementById("Creorder").disabled = false;
            document.getElementById("clearitem").disabled = false;
        }

    }

    function Createorder()
    {
        var table = document.getElementById("tableproducttoOrder");
        var data = [];

        for (var i = 1; i < table.rows.length-1; i++) {
            var row = table.rows[i];
            var obj = {
                PD_ID: row.cells[1].innerHTML,
                PD_NAME: row.cells[2].innerHTML,
                PD_VALUE: row.cells[3].innerHTML,
                PD_PRICE: row.cells[4].innerHTML,
                TP_ID: row.cells[5].innerHTML.substring(0, 5),
                PD_UNIT: row.cells[6].innerHTML
            };
            data.push(obj);
        }

        console.log(data);

        var jsonData = JSON.stringify(data);
        const dataModel = {
            JsonlistProduct: jsonData,
        }
        var result = confirm("ยืนยันการทำรายการ?");
        if (result) {
          $.ajax({
            url: '@Url.Action("InputProductToOrder", "PD_ORDER")',
            data: dataModel,
            dataType: "json",
            type: 'POST',
            success: function (res) {
                if (res["success"]) {
                    alert("ทำรายการสำเร็จ");
                    var orderid = res["orderid"];
                    $("#tbodyPDorder").empty();
                    getoderHistory(orderid);
                    gedatatoder();
                    return;
                } else {
                   alert("ไม่สามารุถทำรายการได้")
                    return;
                }
            },
        });
        }


    }
    function EvnetclickgetorderHistory(e)
    {
        $("#tbodyPDorder").empty();
        document.getElementById("clearitem").disabled = false;
        var OR_ID = $(e).closest('tr').find('.orderidHIS').text().trim();
        console.log(OR_ID);
        getoderHistory(OR_ID);
    }
    function refeshandclear()
    {
        location.reload();
    }
    function getoderHistory(orderid)
    {
        document.getElementById("Creorder").disabled = true;
        $('#orderid').text('เลขที่ Order : ' + orderid);
        const dataModel = {
            oderid: orderid,
        }
        $.ajax({
            url: '@Url.Action("GetOrderData", "PD_ORDER")',
            data: dataModel,
            dataType: "json",
            type: 'POST',
            success: function (res) {
                var jsonString = res["strjsondata"];

                var data = JSON.parse(jsonString);
                console.log(data);
                var countitem = 0;
                var sumpiceall = 0;
                $.each(data, function (i, item) {
                    countitem =  i + 1;
                    sumpiceall = parseFloat(sumpiceall) + parseFloat(item.Price);
                    $('<tr>').html(
                        "<td>" + item.Number + "</td>" +
                        "<td>" + item.ProdcutID + "</td>" +
                        "<td>" + item.ProdcutName + "</td>" +
                        "<td>" + item.Quantity + "</td>" +
                        "<td>" + item.Price + "</td>" +
                        "<td>" + item.Type + "</td>" +
                        "<td>" + item.Unit + "</td> </tr>"
                    ).appendTo('#tableproducttoOrder');
                });
                $("#CountPD").text(countitem);
                $("#CountPcire").text(sumpiceall);
            },
        });
    }
   function gedatatoder()
   {
    
       $("#thobyoorderbottom").empty();
        $.ajax({
            url: '@Url.Action("GetGroupOrderData", "PD_ORDER")',
            dataType: "json",
            type: 'POST',
            success: function (res) {
                var jsonString = res["strjsondata"];
                var data = JSON.parse(jsonString);
                console.log(data);
                $.each(data, function (i, item) {
                    $('<tr>').html(
                        "<td> <input type='button' class='btn btn-success add' onclick='EvnetclickgetorderHistory(this)' value='Show'> </td>" +
                        "<td>" + item.Number + "</td>" +
                        "<td class='orderidHIS'>" + item.OrderID + "</td>" +
                        "<td>" + item.Date + "</td>" +
                        "<td>" + item.pricesum + "</td> </tr>"
                    ).appendTo('#tableOrder');
                });
            },
        });
    }
</script>